"""
team_aliases.py  –  Maps every known alternate team name to the canonical
name used in football-data.co.uk CSVs (our Matches.csv standard).

Covers: FBRef long names, API names, official names, local spellings.
Leagues: England, Scotland, Spain, Germany, Italy, France, Netherlands,
         Belgium, Portugal, Turkey, Norway, Greece, Austria, Switzerland,
         Denmark, Sweden, Poland, Romania, Croatia, Brazil, Argentina,
         Colombia, Chile, Uruguay, Paraguay, Venezuela, Ecuador, Bolivia,
         Peru, MLS, Liga MX, Japan, Korea, China, Australia, India,
         Ghana, Nigeria, South Africa, Egypt, Morocco, Saudi Arabia,
         UAE, Copa Libertadores, Copa Sudamericana, CONCACAF Champions Cup,
         UEFA Champions League, Europa League, Conference League.
"""

from difflib import get_close_matches

ALIASES: dict[str, str] = {

    # ── ENGLAND ───────────────────────────────────────────────────────────────
    "Manchester City FC":           "Man City",
    "Manchester City":              "Man City",
    "Manchester United FC":         "Man United",
    "Manchester United":            "Man United",
    "Man Utd":                      "Man United",
    "Tottenham Hotspur FC":         "Tottenham",
    "Tottenham Hotspur":            "Tottenham",
    "Spurs":                        "Tottenham",
    "Arsenal FC":                   "Arsenal",
    "Chelsea FC":                   "Chelsea",
    "Liverpool FC":                 "Liverpool",
    "Everton FC":                   "Everton",
    "Leicester City FC":            "Leicester",
    "Leicester City":               "Leicester",
    "West Ham United FC":           "West Ham",
    "West Ham United":              "West Ham",
    "Aston Villa FC":               "Aston Villa",
    "Newcastle United FC":          "Newcastle",
    "Newcastle United":             "Newcastle",
    "Brighton & Hove Albion FC":    "Brighton",
    "Brighton & Hove Albion":       "Brighton",
    "Brighton and Hove Albion":     "Brighton",
    "Wolverhampton Wanderers FC":   "Wolves",
    "Wolverhampton Wanderers":      "Wolves",
    "Wolverhampton":                "Wolves",
    "Brentford FC":                 "Brentford",
    "Crystal Palace FC":            "Crystal Palace",
    "Fulham FC":                    "Fulham",
    "AFC Bournemouth":              "Bournemouth",
    "Nottingham Forest FC":         "Nottm Forest",
    "Nottingham Forest":            "Nottm Forest",
    "Burnley FC":                   "Burnley",
    "Luton Town FC":                "Luton",
    "Luton Town":                   "Luton",
    "Sheffield United FC":          "Sheffield Utd",
    "Sheffield United":             "Sheffield Utd",
    "Ipswich Town FC":              "Ipswich",
    "Ipswich Town":                 "Ipswich",
    "Southampton FC":               "Southampton",
    "West Bromwich Albion FC":      "West Brom",
    "West Bromwich Albion":         "West Brom",
    "Leeds United AFC":             "Leeds United",
    "Leeds United FC":              "Leeds United",
    "Norwich City FC":              "Norwich City",
    "Hull City AFC":                "Hull City",
    "Swansea City AFC":             "Swansea City",
    "Swansea City FC":              "Swansea City",
    "Watford FC":                   "Watford",
    "Middlesbrough FC":             "Middlesbrough",
    "Sunderland AFC":               "Sunderland",
    "Sheffield Wednesday FC":       "Sheffield Wednesday",
    "Coventry City FC":             "Coventry City",
    "Bristol City FC":              "Bristol City",
    "Millwall FC":                  "Millwall",
    "Blackburn Rovers FC":          "Blackburn",
    "Blackburn Rovers":             "Blackburn",
    "Preston North End FC":         "Preston",
    "Preston North End":            "Preston",
    "Stoke City FC":                "Stoke",
    "Stoke City":                   "Stoke",
    "Cardiff City FC":              "Cardiff",
    "Cardiff City":                 "Cardiff",
    "Birmingham City FC":           "Birmingham City",
    "Derby County FC":              "Derby County",
    "Portsmouth FC":                "Portsmouth",
    "Oxford United FC":             "Oxford United",
    "Wycombe Wanderers FC":         "Wycombe",
    "Wycombe Wanderers":            "Wycombe",
    "Bristol Rovers FC":            "Bristol Rovers",
    "Bolton Wanderers FC":          "Bolton",
    "Bolton Wanderers":             "Bolton",
    "Charlton Athletic FC":         "Charlton",
    "Charlton Athletic":            "Charlton",
    "Rotherham United FC":          "Rotherham",
    "Rotherham United":             "Rotherham",
    "Plymouth Argyle FC":           "Plymouth",
    "Plymouth Argyle":              "Plymouth",
    "Peterborough United FC":       "Peterborough",
    "Peterborough United":          "Peterborough",
    "Barnsley FC":                  "Barnsley",
    "QPR":                          "Queens Park Rangers",
    "Queens Park Rangers FC":       "Queens Park Rangers",
    "Huddersfield Town AFC":        "Huddersfield",
    "Huddersfield Town":            "Huddersfield",

    # ── SCOTLAND ──────────────────────────────────────────────────────────────
    "Celtic FC":                    "Celtic",
    "Rangers FC":                   "Rangers",
    "Heart of Midlothian FC":       "Hearts",
    "Heart of Midlothian":          "Hearts",
    "Hibernian FC":                 "Hibernian",
    "Aberdeen FC":                  "Aberdeen",
    "Motherwell FC":                "Motherwell",
    "Dundee United FC":             "Dundee United",
    "St Mirren FC":                 "St Mirren",
    "Kilmarnock FC":                "Kilmarnock",
    "Ross County FC":               "Ross County",
    "Livingston FC":                "Livingston",
    "St Johnstone FC":              "St Johnstone",

    # ── SPAIN ─────────────────────────────────────────────────────────────────
    "FC Barcelona":                 "Barcelona",
    "Real Madrid CF":               "Real Madrid",
    "Club Atlético de Madrid":      "Atletico Madrid",
    "Atlético Madrid":              "Atletico Madrid",
    "Atletico de Madrid":           "Atletico Madrid",
    "Atlético de Madrid":           "Atletico Madrid",
    "Sevilla FC":                   "Sevilla",
    "Valencia CF":                  "Valencia",
    "Villarreal CF":                "Villarreal",
    "Athletic Club":                "Athletic Club",
    "Athletic Bilbao":              "Athletic Club",
    "Real Sociedad de Fútbol":      "Real Sociedad",
    "Real Betis Balompié":          "Betis",
    "Real Betis":                   "Betis",
    "CA Osasuna":                   "Osasuna",
    "Girona FC":                    "Girona",
    "UD Las Palmas":                "Las Palmas",
    "Rayo Vallecano":               "Rayo Vallecano",
    "Celta Vigo":                   "Celta",
    "RC Celta":                     "Celta",
    "Getafe CF":                    "Getafe",
    "RCD Espanyol":                 "Espanyol",
    "UD Almería":                   "Almeria",
    "UD Almeria":                   "Almeria",
    "Real Valladolid CF":           "Valladolid",
    "SD Huesca":                    "Huesca",
    "Deportivo Alavés":             "Alaves",
    "Deportivo de La Coruña":       "Deportivo",
    "UD Leganés":                   "Leganes",

    # ── GERMANY ───────────────────────────────────────────────────────────────
    "FC Bayern München":            "Bayern Munich",
    "FC Bayern Munich":             "Bayern Munich",
    "Bayern München":               "Bayern Munich",
    "Borussia Dortmund":            "Dortmund",
    "BVB Dortmund":                 "Dortmund",
    "RB Leipzig":                   "Leipzig",
    "Bayer 04 Leverkusen":          "Leverkusen",
    "Bayer Leverkusen":             "Leverkusen",
    "Eintracht Frankfurt":          "Frankfurt",
    "VfL Wolfsburg":                "Wolfsburg",
    "SC Freiburg":                  "Freiburg",
    "TSG 1899 Hoffenheim":          "Hoffenheim",
    "TSG Hoffenheim":               "Hoffenheim",
    "VfB Stuttgart":                "Stuttgart",
    "SV Werder Bremen":             "Werder Bremen",
    "1. FSV Mainz 05":              "Mainz",
    "Mainz 05":                     "Mainz",
    "Borussia Mönchengladbach":     "Monchengladbach",
    "Borussia M'gladbach":          "Monchengladbach",
    "FC Augsburg":                  "Augsburg",
    "Union Berlin":                 "Union Berlin",
    "1. FC Union Berlin":           "Union Berlin",
    "1. FC Köln":                   "Cologne",
    "FC Köln":                      "Cologne",
    "Hamburger SV":                 "Hamburg",
    "FC Schalke 04":                "Schalke",
    "Hertha BSC":                   "Hertha",
    "Fortuna Düsseldorf":           "Fortuna Dusseldorf",
    "Hannover 96":                  "Hannover",
    "1. FC Nürnberg":               "Nurnberg",
    "SV Darmstadt 98":              "Darmstadt",
    "1. FC Heidenheim":             "Heidenheim",
    "Heidenheim":                   "Heidenheim",

    # ── ITALY ─────────────────────────────────────────────────────────────────
    "Juventus FC":                  "Juventus",
    "AC Milan":                     "AC Milan",
    "FC Internazionale Milano":     "Inter Milan",
    "Internazionale":               "Inter Milan",
    "Inter":                        "Inter Milan",
    "AS Roma":                      "Roma",
    "SSC Napoli":                   "Napoli",
    "SS Lazio":                     "Lazio",
    "Atalanta BC":                  "Atalanta",
    "ACF Fiorentina":               "Fiorentina",
    "Bologna FC 1909":              "Bologna",
    "Bologna FC":                   "Bologna",
    "Torino FC":                    "Torino",
    "Udinese Calcio":               "Udinese",
    "US Sassuolo Calcio":           "Sassuolo",
    "Hellas Verona FC":             "Verona",
    "Hellas Verona":                "Verona",
    "Cagliari Calcio":              "Cagliari",
    "Empoli FC":                    "Empoli",
    "US Lecce":                     "Lecce",
    "Frosinone Calcio":             "Frosinone",
    "Genoa CFC":                    "Genoa",
    "Venezia FC":                   "Venezia",
    "Spezia Calcio":                "Spezia",
    "Monza":                        "Monza",
    "AC Monza":                     "Monza",

    # ── FRANCE ────────────────────────────────────────────────────────────────
    "Olympique de Marseille":       "Marseille",
    "Paris Saint-Germain FC":       "Paris SG",
    "Paris Saint-Germain":          "Paris SG",
    "PSG":                          "Paris SG",
    "Olympique Lyonnais":           "Lyon",
    "AS Monaco FC":                 "Monaco",
    "AS Monaco":                    "Monaco",
    "LOSC Lille":                   "Lille",
    "Stade Rennais FC":             "Rennes",
    "OGC Nice":                     "Nice",
    "RC Lens":                      "Lens",
    "Toulouse FC":                  "Toulouse",
    "Montpellier HSC":              "Montpellier",
    "Stade Brestois 29":            "Brest",
    "Stade de Reims":               "Reims",
    "FC Nantes":                    "Nantes",
    "Girondins de Bordeaux":        "Bordeaux",
    "AS Saint-Étienne":             "Saint-Etienne",
    "AJ Auxerre":                   "Auxerre",
    "Le Havre AC":                  "Le Havre",

    # ── NETHERLANDS ───────────────────────────────────────────────────────────
    "AFC Ajax":                     "Ajax",
    "PSV Eindhoven":                "PSV",
    "Feyenoord Rotterdam":          "Feyenoord",
    "AZ Alkmaar":                   "AZ Alkmaar",
    "FC Utrecht":                   "Utrecht",
    "FC Twente":                    "Twente",
    "NEC Nijmegen":                 "NEC Nijmegen",
    "Heracles Almelo":              "Heracles",
    "Sparta Rotterdam":             "Sparta Rotterdam",

    # ── BELGIUM ───────────────────────────────────────────────────────────────
    "RSC Anderlecht":               "Anderlecht",
    "Club Brugge KV":               "Club Brugge",
    "KAA Gent":                     "Gent",
    "Standard de Liège":            "Standard Liege",
    "Standard Liège":               "Standard Liege",
    "Royal Antwerp FC":             "Antwerp",
    "KRC Genk":                     "Genk",
    "Cercle Brugge KSV":            "Cercle Brugge",
    "Sint-Truidense VV":            "Sint-Truiden",
    "KV Mechelen":                  "Mechelen",

    # ── PORTUGAL ──────────────────────────────────────────────────────────────
    "SL Benfica":                   "Benfica",
    "FC Porto":                     "Porto",
    "Sporting CP":                  "Sporting CP",
    "Sporting Clube de Portugal":   "Sporting CP",
    "SC Braga":                     "Braga",
    "Vitória SC":                   "Vitoria",
    "Gil Vicente FC":               "Gil Vicente",
    "FC Famalicão":                 "Famalicao",
    "FC Arouca":                    "Arouca",
    "Boavista FC":                  "Boavista",
    "GD Estoril Praia":             "Estoril",

    # ── TURKEY ────────────────────────────────────────────────────────────────
    "Galatasaray SK":               "Galatasaray",
    "Fenerbahçe SK":                "Fenerbahce",
    "Fenerbahçe":                   "Fenerbahce",
    "Beşiktaş JK":                  "Besiktas",
    "Beşiktaş":                     "Besiktas",
    "Trabzonspor AŞ":               "Trabzonspor",
    "Kasımpaşa SK":                 "Kasimpasa",
    "Kasımpaşa":                    "Kasimpasa",
    "Ankaragücü":                   "Ankaragucu",
    "Başakşehir FK":                "Istanbul Basaksehir",
    "Istanbul Basaksehir FK":       "Istanbul Basaksehir",
    "Gaziantep FK":                 "Gaziantep",

    # ── NORWAY ────────────────────────────────────────────────────────────────
    "FK Bodø/Glimt":                "Bodo/Glimt",
    "Bodø/Glimt":                   "Bodo/Glimt",
    "Molde FK":                     "Molde",
    "SK Brann":                     "Brann",
    "Rosenborg BK":                 "Rosenborg",
    "Viking FK":                    "Viking",
    "Lillestrøm SK":                "Lillestrom",
    "Strømsgodset IF":              "Stromsgodset",
    "FK Haugesund":                 "Haugesund",
    "Vålerenga FK":                 "Valerenga",
    "Sarpsborg 08 FF":              "Sarpsborg",
    "Tromsø IL":                    "Tromso",
    "FK Fredrikstad":               "Fredrikstad",

    # ── UEFA CLUBS ────────────────────────────────────────────────────────────
    "Shakhtar Donetsk":             "Shakhtar Donetsk",
    "Dynamo Kyiv":                  "Dynamo Kyiv",
    "Dinamo Zagreb":                "Dinamo Zagreb",
    "Slavia Prague":                "Slavia Prague",
    "Sparta Prague":                "Sparta Prague",
    "Red Bull Salzburg":            "Red Bull Salzburg",
    "FC Salzburg":                  "Red Bull Salzburg",
    "Legia Warszawa":               "Legia Warsaw",
    "Lech Poznań":                  "Lech Poznan",
    "Ferencváros TC":               "Ferencvaros",
    "Olympiacos CFP":               "Olympiacos",
    "PAOK FC":                      "PAOK",
    "AEK Athens FC":                "AEK Athens",
    "Rapid Wien":                   "Rapid Vienna",
    "BSC Young Boys":               "Young Boys",
    "FC Basel 1893":                "FC Basel",
    "FC Zürich":                    "FC Zurich",
    "FC Copenhagen":                "FC Copenhagen",
    "FC Midtjylland":               "Midtjylland",
    "Brøndby IF":                   "Brondby",
    "Malmö FF":                     "Malmo FF",
    "Djurgårdens IF":               "Djurgarden",
    "IFK Göteborg":                 "IFK Gothenburg",

    # ── GHANA PREMIER LEAGUE ──────────────────────────────────────────────────
    "Accra Hearts of Oak SC":       "Hearts of Oak",
    "Hearts of Oak":                "Hearts of Oak",
    "Kumasi Asante Kotoko SC":      "Asante Kotoko",
    "Asante Kotoko":                "Asante Kotoko",
    "Asante Kotoko SC":             "Asante Kotoko",
    "Kotoko":                       "Asante Kotoko",
    "Medeama SC":                   "Medeama",
    "Aduana Stars FC":              "Aduana Stars",
    "Aduana FC":                    "Aduana Stars",
    "Berekum Chelsea":              "Berekum Chelsea",
    "Dreams FC":                    "Dreams FC",
    "Legon Cities FC":              "Legon Cities",
    "Bechem United FC":             "Bechem United",
    "Real Tamale United":           "Real Tamale United",
    "Tamale City FC":               "Tamale City",
    "Karela United FC":             "Karela United",
    "Bibiani Gold Stars":           "Gold Stars",
    "Gold Stars FC":                "Gold Stars",
    "Nsoatreman FC":                "Nsoatreman",
    "Bofoakwa Tano":                "Bofoakwa Tano",
    "Techiman Eleven Wonders":      "Eleven Wonders",
    "King Faisal Babes":            "King Faisal",
    "King Faisal FC":               "King Faisal",
    "Accra Lions FC":               "Accra Lions",
    "Accra Great Olympics":         "Great Olympics",
    "Great Olympics":               "Great Olympics",
    "WAFA SC":                      "WAFA",
    "Vision FC":                    "Vision FC",
    "Accra Lions":                  "Accra Lions",
    "Heart of Lions":               "Heart of Lions",
    "Tema Youth":                   "Tema Youth",
    "Inter Allies":                 "Inter Allies",
    "Elmina Sharks":                "Elmina Sharks",
    "Liberty Professionals":        "Liberty Professionals",
    "Wa All Stars":                 "All Stars",
    "Asokwa Deportivo":             "Asokwa Deportivo",

    # ── NIGERIA PREMIER LEAGUE ────────────────────────────────────────────────
    "Enyimba International FC":     "Enyimba",
    "Enyimba FC":                   "Enyimba",
    "Kano Pillars FC":              "Kano Pillars",
    "Rivers United FC":             "Rivers United",
    "Shooting Stars SC":            "Shooting Stars",
    "Heartland FC":                 "Heartland",
    "Plateau United FC":            "Plateau United",
    "Lobi Stars FC":                "Lobi Stars",
    "Nasarawa United FC":           "Nasarawa United",
    "Remo Stars FC":                "Remo Stars",
    "Sunshine Stars FC":            "Sunshine Stars",
    "Akwa United FC":               "Akwa United",
    "Enugu Rangers":                "Enugu Rangers",
    "MFM FC":                       "MFM FC",
    "Abia Warriors FC":             "Abia Warriors",
    "Bendel Insurance FC":          "Bendel Insurance",
    "Warri Wolves FC":              "Warri Wolves",

    # ── SOUTH AFRICA ──────────────────────────────────────────────────────────
    "Mamelodi Sundowns FC":         "Mamelodi Sundowns",
    "Kaizer Chiefs FC":             "Kaizer Chiefs",
    "Orlando Pirates FC":           "Orlando Pirates",
    "Cape Town City FC":            "Cape Town City",
    "SuperSport United FC":         "SuperSport United",
    "Stellenbosch FC":              "Stellenbosch",
    "AmaZulu FC":                   "AmaZulu",
    "Golden Arrows FC":             "Golden Arrows",
    "Sekhukhune United FC":         "Sekhukhune United",
    "Chippa United FC":             "Chippa United",

    # ── EGYPT ─────────────────────────────────────────────────────────────────
    "Al Ahly SC":                   "Al Ahly",
    "Zamalek SC":                   "Zamalek",
    "Pyramids FC":                  "Pyramids",
    "Al Masry SC":                  "Al Masry",
    "El Ismaily SC":                "Ismaily",

    # ── MOROCCO ───────────────────────────────────────────────────────────────
    "Wydad Athletic Club":          "Wydad",
    "Raja Club Athletic":           "Raja Casablanca",
    "FUS Rabat":                    "FUS Rabat",
    "RS Berkane":                   "RS Berkane",

    # ── CAF CHAMPIONS LEAGUE ─────────────────────────────────────────────────
    "TP Mazembe":                   "TP Mazembe",
    "Al-Ahly SC":                   "Al Ahly",
    "Esperance Sportive de Tunis":  "Esperance Tunis",
    "ES Tunis":                     "Esperance Tunis",
    "Simba SC":                     "Simba SC",
    "Young Africans SC":            "Young Africans",
    "Yanga SC":                     "Young Africans",
    "Wydad Casablanca":             "Wydad",
    "Sundowns":                     "Mamelodi Sundowns",

    # ── COPA LIBERTADORES / SUDAMERICANA ─────────────────────────────────────
    "Deportivo La Guaira":          "Dep. La Guaira",
    "Dep. La Guaira":               "Dep. La Guaira",
    "Caracas FC":                   "Caracas FC",
    "Deportivo Táchira FC":         "Dep. Tachira",
    "Monagas SC":                   "Monagas",
    "Barcelona SC":                 "Barcelona SC",
    "LDU Quito":                    "LDU Quito",
    "Liga Deportiva Universitaria": "LDU Quito",
    "Independiente del Valle":      "Indep. del Valle",
    "CS Emelec":                    "Emelec",
    "CSD Aucas":                    "Aucas",
    "Club Bolívar":                 "Bolivar",
    "Bolívar":                      "Bolivar",
    "Club Always Ready":            "Always Ready",
    "Always Ready":                 "Always Ready",
    "Independiente Petrolero":      "Indep. Petrolero",
    "Ind. Petrolero":               "Indep. Petrolero",
    "The Strongest":                "The Strongest",
    "Club Wilstermann":             "Wilstermann",
    "Club Universitario de Deportes": "Universitario",
    "Universitario de Deportes":    "Universitario",
    "Club Alianza Lima":            "Alianza Lima",
    "FBC Melgar":                   "Melgar",
    "Sporting Cristal":             "Sporting Cristal",
    "Alianza Atlético":             "Alianza Atletico",
    "Alianza Atlético de Sullana":  "Alianza Atletico",
    "Club Universidad Católica":    "Universidad Catolica",
    "Universidad Católica":         "Universidad Catolica",
    "Colo-Colo":                    "Colo-Colo",
    "Huachipato":                   "Huachipato",
    "O'Higgins FC":                 "O'Higgins",
    "Club Atlético Peñarol":        "Penarol",
    "Club Nacional de Football":    "Nacional",
    "Boston River":                 "Boston River",
    "Millonarios FC":               "Millonarios",
    "Deportes Tolima":              "Deportes Tolima",
    "Atlético Nacional":            "Atletico Nacional",
    "Club Olimpia":                 "Olimpia",
    "Club Cerro Porteño":           "Cerro Porteno",
    "Club Guaraní":                 "Guarani",
    "Club Sol de América":          "Sol de America",
    "Independiente Rivadavia":      "Ind. Rivadavia",
    "Ind. Rivadavia":               "Ind. Rivadavia",
    "Cruzeiro EC":                  "Cruzeiro",
    "Vasco da Gama":                "Vasco da Gama",
    "Barracas Central":             "Barracas Central",
    "CA Tigre":                     "Tigre",
    "Club de Deportes Cobreloa":    "Cobreloa",
    "Club Atlético River Plate":    "River Plate",
    "Club Atlético Boca Juniors":   "Boca Juniors",
    "Club Deportivo Los Millionarios": "Millonarios",
    "Junior FC":                    "Junior de Barranquilla",
    "Atletico Bucaramanga":         "Bucaramanga",
    "Club Universidad de Chile":    "Universidad de Chile",
    "Everton de Viña del Mar":      "Everton de Vina",
    "CD Palestino":                 "Palestino",
    "Ñublense":                     "Nublense",
    "Club Atlético Rentistas":      "Rentistas",
    "Defensor Sporting Club":       "Defensor Sporting",
    "Club Libertad":                "Libertad",

    # ── CONCACAF CHAMPIONS CUP ───────────────────────────────────────────────
    "Nashville SC":                 "Nashville SC",
    "Club América":                 "Club America",
    "Cruz Azul":                    "Cruz Azul",
    "Deportivo Saprissa":           "Saprissa",
    "Comunicaciones FC":            "Comunicaciones",
    "New England Revolution":       "New England Revolution",
    "CF Montréal":                  "CF Montreal",
    "Los Angeles Galaxy":           "LA Galaxy",
    "Los Angeles FC":               "LAFC",
    "Atlanta United FC":            "Atlanta United",
    "Seattle Sounders FC":          "Seattle Sounders",
    "Portland Timbers":             "Portland Timbers",
    "Inter Miami CF":               "Inter Miami",
    "Columbus Crew SC":             "Columbus Crew",
    "Columbus Crew":                "Columbus Crew",
    "Chicago Fire FC":              "Chicago Fire",
    "D.C. United":                  "DC United",
    "Orlando City SC":              "Orlando City",
    "Club Tigres UANL":             "Tigres",
    "CF Monterrey":                 "Monterrey",
    "Club Universidad Nacional":    "Pumas UNAM",
    "Club Deportivo Toluca":        "Toluca",

    # ── SAUDI ARABIA ─────────────────────────────────────────────────────────
    "Al-Hilal SFC":                 "Al-Hilal",
    "Al-Hilal":                     "Al-Hilal",
    "Al-Nassr FC":                  "Al-Nassr",
    "Al-Nassr":                     "Al-Nassr",
    "Al-Ittihad Club":              "Al-Ittihad",
    "Al-Ahli Saudi FC":             "Al-Ahli",
    "Al-Shabab FC":                 "Al-Shabab",
    "Al-Ettifaq FC":                "Al-Ettifaq",
    "Al-Fateh SC":                  "Al-Fateh",
    "Al-Taawoun FC":                "Al-Taawoun",
    "Damac FC":                     "Damac",
    "Al-Wehda FC":                  "Al-Wehda",
    "Al-Khaleej":                   "Al-Khaleej",

    # ── INDIA ────────────────────────────────────────────────────────────────
    "Mumbai City FC":               "Mumbai City",
    "FC Goa":                       "FC Goa",
    "ATK Mohun Bagan":              "Mohun Bagan",
    "Mohun Bagan Super Giant":      "Mohun Bagan",
    "Bengaluru FC":                 "Bengaluru",
    "Kerala Blasters FC":           "Kerala Blasters",
    "East Bengal FC":               "East Bengal",
    "Chennaiyin FC":                "Chennaiyin",
    "NorthEast United FC":          "NorthEast United",
    "Jamshedpur FC":                "Jamshedpur",
    "Hyderabad FC":                 "Hyderabad",
    "Odisha FC":                    "Odisha",
    "Punjab FC":                    "Punjab FC",

    # ── CHINA ────────────────────────────────────────────────────────────────
    "Shanghai Port FC":             "Shanghai Port",
    "Shandong Taishan FC":          "Shandong Taishan",
    "Beijing Guoan FC":             "Beijing Guoan",
    "Wuhan Three Towns FC":         "Wuhan Three Towns",
    "Zhejiang FC":                  "Zhejiang",
    "Chengdu Rongcheng FC":         "Chengdu Rongcheng",

    # ── KOREA ────────────────────────────────────────────────────────────────
    "Jeonbuk Hyundai Motors FC":    "Jeonbuk Motors",
    "Ulsan Hyundai FC":             "Ulsan Hyundai",
    "Jeonbuk Motors FC":            "Jeonbuk Motors",

    # ── AUSTRALIA ────────────────────────────────────────────────────────────
    "Melbourne City FC":            "Melbourne City",
    "Sydney FC":                    "Sydney FC",
    "Melbourne Victory FC":         "Melbourne Victory",
    "Western Sydney Wanderers FC":  "Western Sydney Wanderers",
    "Adelaide United FC":           "Adelaide United",
    "Brisbane Roar FC":             "Brisbane Roar",
    "Wellington Phoenix FC":        "Wellington Phoenix",
    "Macarthur FC":                 "Macarthur",
    "Western United FC":            "Western United",

}

# Lowercase lookup for fast matching
_LOWER: dict[str, str] = {k.lower(): v for k, v in ALIASES.items()}


def normalise(name: str, known_teams: list = None) -> str:
    """
    Return the canonical team name used in Matches.csv.

    1. Exact match in ALIASES
    2. Case-insensitive match
    3. Fuzzy match against known_teams (if provided)
    4. Return original unchanged
    """
    if not name:
        return name

    if name in ALIASES:
        return ALIASES[name]

    lower = name.lower().strip()
    if lower in _LOWER:
        return _LOWER[lower]

    if known_teams:
        close_alias = get_close_matches(name, list(ALIASES.keys()), n=1, cutoff=0.82)
        if close_alias:
            return ALIASES[close_alias[0]]
        close_team = get_close_matches(name, known_teams, n=1, cutoff=0.80)
        if close_team:
            return close_team[0]

    return name
